//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ErrorPage
{

    /// <summary>
    /// Head1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlHead Head1;

    /// <summary>
    /// form1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;

    /// <summary>
    /// ApplicationTitle control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal ApplicationTitle;

    /// <summary>
    /// InfoMessagesPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal InfoMessagesPanel;

    /// <summary>
    /// Table1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Table Table1;

    /// <summary>
    /// TableRow2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TableRow TableRow2;

    /// <summary>
    /// ViewSite control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TableCell ViewSite;

    /// <summary>
    /// ErrorTitleLiteral control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal ErrorTitleLiteral;

    /// <summary>
    /// ErrorPanel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel ErrorPanel;

    /// <summary>
    /// ReportResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder ReportResult;

    /// <summary>
    /// ApologizeMessage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder ApologizeMessage;

    /// <summary>
    /// HyperLink1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HyperLink HyperLink1;

    /// <summary>
    /// NavigateToStart control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.LinkButton NavigateToStart;

    /// <summary>
    /// PopupReportResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder PopupReportResult;

    /// <summary>
    /// PopupApologizeMessage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder PopupApologizeMessage;

    /// <summary>
    /// HyperLink2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HyperLink HyperLink2;

    /// <summary>
    /// Details control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel Details;

    /// <summary>
    /// DetailsText control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Literal DetailsText;

    /// <summary>
    /// ReportForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel ReportForm;

    /// <summary>
    /// DescriptionTextBox control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.TextBox DescriptionTextBox;

    /// <summary>
    /// ReportButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// 目标仓库 modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Button ReportButton;
}
